project:
  type: website
  output-dir: docs
  title: "DUIVENBOS (HERZELE)"
  preview:
    port: 4200

website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Betrokken partijen" 
        file: 1_betrokken_partijen.qmd
      - text: "Waarom deze plannen?"
        file: 2_plannen.qmd
      - text: "Gevolgen van de plannen" 
        file: 3_gevolgen.qmd 
      - text: "Vragen van buurtbewoners" 
        file: 4_vragen.qmd 

lightbox: true

format:
  html:
    theme: flatly  
    css: styles.css
    toc: true
    toc-title: Inhoudstafel
    toc_float: true
    toc-depth: 5
    toc-location: left
    toc-expand: true
    number-sections: false
    page-layout: full
    embed-resources: true
    smooth-scroll: true
    code-fold: true
    code-link: true
    

bibliography: references.bib
csl: apa-single-spaced.csl

reference-location: margin
citation-location: margin
    

editor: source

sidebar:
     style: "floating"
     search: true
     alignment: left
     border: true

notebook-links: true
lang: nl

grid:
   margin-width: 350px
   sidebar-width: 350px
   gutter-width: 2.5em
   body-width: 1000px

